### PR TITLE
feat: support `KeycloakVersion`

### PR DESCRIPTION
**Pull request by pahud**
With this PR, we are allowed to specify the `KeycloakVersion` in the construct property.

# BREAKING CHANGES
`keycloakVerison` is now a mandatory property. You must specify this value when you upgrade to the latest version of this construct. Make sure you backup everything including the database before you deploy with the upgrade.

To avoid accidental database removal, now the database `deletionProtection` is enabled with the `removalPolicy` as `RETAIN`. Please make sure you backup the database before you upgrade this construct library. Always run `cdk diff` to see what will be changed before `cdk deploy`.

### CODE REVIEW

**Comment by pahud** [comment]
`15.0.2` can successfully be deployed in my environment(`ap-northeast-1`)

圖片

**Review by wchaws — CHANGES_REQUESTED** [review]
There're 3 `cdk.RemovalPolicy.DESTROY` in the code. You only fixed one.

**Comment by pahud** [comment]
> There're 3 `cdk.RemovalPolicy.DESTROY` in the code. You only fixed one.

All addressed. Please take a look again.

**Review by wchaws — APPROVED** [review]
LGTM

**Pull request merged**
