### PR TITLE
feat: adds version 16.1.1

### PR DESCRIPTION
**Pull request by adamstortz**
Fixes #

### CODE REVIEW

**Comment by wchaws** [comment]
1. Please fix build error firstly.
2. You need to change the registry from `jobss/keycloak` to [quay.io/keycloak/keycloak](http://quay.io/keycloak/keycloak). So please update this map at https://github.com/aws-samples/cdk-keycloak/blob/29fb71973a7e08426248f1f463e4daa76ecb24ec/src/keycloak.ts#L79

**Review by wchaws — CHANGES_REQUESTED** [review]
1. Please fix build error firstly.
2. You need to change the registry from `jobss/keycloak` to [quay.io/keycloak/keycloak](http://quay.io/keycloak/keycloak). So please update this map at https://github.com/aws-samples/cdk-keycloak/blob/29fb71973a7e08426248f1f463e4daa76ecb24ec/src/keycloak.ts#L79

**Comment by adamstortz** [comment]
@wchaws, I have pushed the changes that were breaking the build.

As for the registry change, 16.1.1 is the latest version in the jboss/keycloak registry.  17.x and higher don't work in the current construct, so more changes will be necessary to support the versions in quay.io.  So I think we should wait until those changes are implemented and add those newer versions and the quay.io registry on a new PR.

If you want to move forward with the quay.io change now, what would the proper registry be for the aws-cn segment?  Can we use quay.io for both?

**Comment by wchaws** [comment]
> As for the registry change, 16.1.1 is the latest version in the jboss/keycloak registry. 17.x and higher don't work in the current construct, so more changes will be necessary to support the versions in quay.io. So I think we should wait until those changes are implemented and add those newer versions and the quay.io registry on a new PR.
> 
> If you want to move forward with the quay.io change now, what would the proper registry be for the aws-cn segment? Can we use quay.io for both?

Good point!

The internet connection quality between china region(aws-cn) and docker.io/quay.io is not stable for some reason. So, currently solution is setting up a mirror of keycloak image with a private ECR registry. For now, I think you could ignore china region since there're rare customers using keycloak in china.

I will merge this PR once build is passed.

**Pull request merged**
