### PR TITLE
Update Keycloak version to 15.0.2

### PR DESCRIPTION
**Pull request by takuan-osho**
This PR will update Keycloak image's version to 15.0.2, which is the latest version.

refs: 

- https://github.com/keycloak/keycloak/releases/tag/15.0.2
- https://quay.io/repository/keycloak/keycloak?tab=tags

### CODE REVIEW

**Comment by pahud** [comment]
Maybe we should expose a `version` construct property and allow user to specify the version. What do you think?

copy @wchaws

**Comment by wchaws** [comment]
> Maybe we should expose a `version` construct property and allow user to specify the version. What do you think?
> 
> copy @wchaws

I'm ok with that.

**Comment by pahud** [comment]
close in favor of #136

**Comment by pahud** [comment]
@takuan-osho  please let us know if the new feature works with you.

**Pull request closed without merging**
