### PR TITLE
feat: update keyloak new version

### PR DESCRIPTION
**Pull request by guan840912**
feat: update keyloak new version

### CODE REVIEW

**Comment by pahud** [comment]
Thanks! Will approve when https://github.com/nwcdlabs/container-mirror/pull/127 is merged.

**Review by pahud — APPROVED** [review]

**Comment by pahud** [comment]
copy @wchaws

**Comment by pahud** [comment]
Hi @guan840912 

When version `0.2.3` is published, can you help deploy cdk-keycloak again in your environment and make sure the keycloak 12.0.4 is working?

Thanks.

**Comment by guan840912** [comment]
deploy version `0.2.3 `.
截圖 2021-04-19 下午6 20 29

working !!! 
thanks

cc @pahud

**Pull request merged**
